# Generated by Django 6.1 on 2026-10-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioVisitorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visitors', models.PositiveBigIntegerField(default=10003)),
            ],
            options={
                'verbose_name': 'portfolio visitor count',
                'verbose_name_plural': 'portfolio visitor count',
            },
        ),
    ]
