# Generated by Django 6.1 on 2026-10-04 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.CharField(max_length=260)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('django', 'Django'), ('python', 'Python'), ('backend', 'Backend development'), ('api', 'REST APIs'), ('learning', 'Learning journey')], default='learning', max_length=16)),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('reading_time_minutes', models.PositiveSmallIntegerField(default=3)),
                ('tags', models.CharField(blank=True, max_length=220)),
            ],
            options={
                'ordering': ('-published_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='ChatbotKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('content', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'chatbot knowledge entry',
                'ordering': ('display_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('contact', 'Contact form'), ('text', 'Text-style message'), ('feedback', 'Feedback')], max_length=12)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('is_read', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='JourneyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('organization', models.CharField(blank=True, max_length=140)),
                ('period', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField()),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('django', 'Django'), ('api', 'REST API'), ('python', 'Python'), ('flask', 'Flask'), ('web', 'Web application')], default='django', max_length=12)),
                ('thumbnail', models.ImageField(blank=True, upload_to='projects/')),
                ('image_alt', models.CharField(blank=True, max_length=180)),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated technologies', max_length=240)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('technical_highlights', models.TextField(blank=True, help_text='One highlight per line')),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('project_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-featured', 'display_order', '-project_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('alt_text', models.CharField(max_length=180)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='portfolio.project')),
            ],
            options={
                'ordering': ('display_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('database', 'Database'), ('frontend', 'Frontend'), ('tools', 'Tools'), ('learning', 'Currently learning')], max_length=16)),
                ('status', models.CharField(choices=[('project', 'Building projects'), ('working', 'Working knowledge'), ('learning', 'Currently learning')], default='learning', max_length=12)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('category', 'display_order', 'name'),
                'unique_together': {('name', 'category')},
            },
        ),
    ]
