# Generated by Django 6.1 on 2026-10-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blogpost_chatbotknowledge_contactmessage_journeyitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=140)),
                ('bio', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('education', models.CharField(blank=True, max_length=180)),
                ('institution', models.CharField(blank=True, max_length=180)),
                ('study_year', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, upload_to='profile/')),
                ('resume_file', models.FileField(blank=True, upload_to='resume/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'portfolio profile',
                'verbose_name_plural': 'portfolio profile',
            },
        ),
    ]
